name: albatross
dependencies:
- python>=3.8
- emcee
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- xarray
- pyproj
- basemap
- sphinx
- pip:
  - emcee
  - sphinx-autobuild
  - sphinx_rtd_theme
