load("@aspect_rules_lint//format:defs.bzl", "format_multirun")
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

package(default_visibility = ["//:__subpackages__"])

native_binary(
    name = "clang-format",
    src = select({
        "@bazel_tools//src/conditions:darwin_arm64": "@aarch64-darwin-llvm20//:clang-format",
        "@bazel_tools//src/conditions:linux_x86_64": "@x86_64-linux-llvm20//:clang-format",
        "//conditions:default": "@x86_64-linux-llvm20//:clang-format",
    }),
    out = "clang-format",
)

format_multirun(
    name = "format",
    c = ":clang-format",
    cc = ":clang-format",
    starlark = "@buildifier_prebuilt//:buildifier",
    visibility = ["//:__subpackages__"],
)
